/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DoctorList } from "./DoctorList";
import { DoctorListCountArgs } from "./DoctorListCountArgs";
import { DoctorListFindManyArgs } from "./DoctorListFindManyArgs";
import { DoctorListFindUniqueArgs } from "./DoctorListFindUniqueArgs";
import { DeleteDoctorListArgs } from "./DeleteDoctorListArgs";
import { DoctorListService } from "../doctorList.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DoctorList)
export class DoctorListResolverBase {
  constructor(
    protected readonly service: DoctorListService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DoctorList",
    action: "read",
    possession: "any",
  })
  async _doctorListsMeta(
    @graphql.Args() args: DoctorListCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DoctorList])
  @nestAccessControl.UseRoles({
    resource: "DoctorList",
    action: "read",
    possession: "any",
  })
  async doctorLists(
    @graphql.Args() args: DoctorListFindManyArgs
  ): Promise<DoctorList[]> {
    return this.service.doctorLists(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DoctorList, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DoctorList",
    action: "read",
    possession: "own",
  })
  async doctorList(
    @graphql.Args() args: DoctorListFindUniqueArgs
  ): Promise<DoctorList | null> {
    const result = await this.service.doctorList(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DoctorList)
  @nestAccessControl.UseRoles({
    resource: "DoctorList",
    action: "delete",
    possession: "any",
  })
  async deleteDoctorList(
    @graphql.Args() args: DeleteDoctorListArgs
  ): Promise<DoctorList | null> {
    try {
      return await this.service.deleteDoctorList(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
