/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  DoctorPersonalData as PrismaDoctorPersonalData,
} from "@prisma/client";
import { DoctorPersonalDataCreateInput } from "./DoctorPersonalDataCreateInput";
import { DoctorPersonalData } from "./DoctorPersonalData";

export class DoctorPersonalDataServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DoctorPersonalDataCountArgs, "select">
  ): Promise<number> {
    return this.prisma.doctorPersonalData.count(args);
  }

  async doctorPersonalDataItems(
    args: Prisma.DoctorPersonalDataFindManyArgs
  ): Promise<PrismaDoctorPersonalData[]> {
    return this.prisma.doctorPersonalData.findMany(args);
  }
  async doctorPersonalData(
    args: Prisma.DoctorPersonalDataFindUniqueArgs
  ): Promise<PrismaDoctorPersonalData | null> {
    return this.prisma.doctorPersonalData.findUnique(args);
  }
  async createDoctorPersonalData(
    args: Prisma.DoctorPersonalDataCreateArgs
  ): Promise<PrismaDoctorPersonalData> {
    return this.prisma.doctorPersonalData.create(args);
  }
  async updateDoctorPersonalData(
    args: Prisma.DoctorPersonalDataUpdateArgs
  ): Promise<PrismaDoctorPersonalData> {
    return this.prisma.doctorPersonalData.update(args);
  }
  async deleteDoctorPersonalData(
    args: Prisma.DoctorPersonalDataDeleteArgs
  ): Promise<PrismaDoctorPersonalData> {
    return this.prisma.doctorPersonalData.delete(args);
  }
  async CreateDoctorPersonalData(args: string): Promise<string> {
    throw new Error("Not implemented");
  }
  async CreateDoctorPersonalDataEntry(
    args: DoctorPersonalDataCreateInput
  ): Promise<DoctorPersonalData> {
    throw new Error("Not implemented");
  }
}
