/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PatientTreatment } from "./PatientTreatment";
import { PatientTreatmentCountArgs } from "./PatientTreatmentCountArgs";
import { PatientTreatmentFindManyArgs } from "./PatientTreatmentFindManyArgs";
import { PatientTreatmentFindUniqueArgs } from "./PatientTreatmentFindUniqueArgs";
import { DeletePatientTreatmentArgs } from "./DeletePatientTreatmentArgs";
import { PatientTreatmentCreateInput } from "./PatientTreatmentCreateInput";
import { PatientTreatmentService } from "../patientTreatment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PatientTreatment)
export class PatientTreatmentResolverBase {
  constructor(
    protected readonly service: PatientTreatmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PatientTreatment",
    action: "read",
    possession: "any",
  })
  async _patientTreatmentsMeta(
    @graphql.Args() args: PatientTreatmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PatientTreatment])
  @nestAccessControl.UseRoles({
    resource: "PatientTreatment",
    action: "read",
    possession: "any",
  })
  async patientTreatments(
    @graphql.Args() args: PatientTreatmentFindManyArgs
  ): Promise<PatientTreatment[]> {
    return this.service.patientTreatments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PatientTreatment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PatientTreatment",
    action: "read",
    possession: "own",
  })
  async patientTreatment(
    @graphql.Args() args: PatientTreatmentFindUniqueArgs
  ): Promise<PatientTreatment | null> {
    const result = await this.service.patientTreatment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PatientTreatment)
  @nestAccessControl.UseRoles({
    resource: "PatientTreatment",
    action: "delete",
    possession: "any",
  })
  async deletePatientTreatment(
    @graphql.Args() args: DeletePatientTreatmentArgs
  ): Promise<PatientTreatment | null> {
    try {
      return await this.service.deletePatientTreatment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PatientTreatment)
  async CreatePatientTreatmentEntry(
    @graphql.Args()
    args: PatientTreatmentCreateInput
  ): Promise<PatientTreatment> {
    return this.service.CreatePatientTreatmentEntry(args);
  }
}
