/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DoctorMedicalRecords } from "./DoctorMedicalRecords";
import { DoctorMedicalRecordsCountArgs } from "./DoctorMedicalRecordsCountArgs";
import { DoctorMedicalRecordsFindManyArgs } from "./DoctorMedicalRecordsFindManyArgs";
import { DoctorMedicalRecordsFindUniqueArgs } from "./DoctorMedicalRecordsFindUniqueArgs";
import { DeleteDoctorMedicalRecordsArgs } from "./DeleteDoctorMedicalRecordsArgs";
import { DoctorMedicalRecordsCreateInput } from "./DoctorMedicalRecordsCreateInput";
import { DoctorMedicalRecordsService } from "../doctorMedicalRecords.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DoctorMedicalRecords)
export class DoctorMedicalRecordsResolverBase {
  constructor(
    protected readonly service: DoctorMedicalRecordsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DoctorMedicalRecords",
    action: "read",
    possession: "any",
  })
  async _doctorMedicalRecordsItemsMeta(
    @graphql.Args() args: DoctorMedicalRecordsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DoctorMedicalRecords])
  @nestAccessControl.UseRoles({
    resource: "DoctorMedicalRecords",
    action: "read",
    possession: "any",
  })
  async doctorMedicalRecordsItems(
    @graphql.Args() args: DoctorMedicalRecordsFindManyArgs
  ): Promise<DoctorMedicalRecords[]> {
    return this.service.doctorMedicalRecordsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DoctorMedicalRecords, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DoctorMedicalRecords",
    action: "read",
    possession: "own",
  })
  async doctorMedicalRecords(
    @graphql.Args() args: DoctorMedicalRecordsFindUniqueArgs
  ): Promise<DoctorMedicalRecords | null> {
    const result = await this.service.doctorMedicalRecords(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DoctorMedicalRecords)
  @nestAccessControl.UseRoles({
    resource: "DoctorMedicalRecords",
    action: "delete",
    possession: "any",
  })
  async deleteDoctorMedicalRecords(
    @graphql.Args() args: DeleteDoctorMedicalRecordsArgs
  ): Promise<DoctorMedicalRecords | null> {
    try {
      return await this.service.deleteDoctorMedicalRecords(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DoctorMedicalRecords)
  async CreateDoctorMedicalRecordsEntry(
    @graphql.Args()
    args: DoctorMedicalRecordsCreateInput
  ): Promise<DoctorMedicalRecords> {
    return this.service.CreateDoctorMedicalRecordsEntry(args);
  }
}
